# frozen_string_literal: true

import '../../fastlane/Fastfile'

default_platform(:ios)

platform :ios do
  desc 'Dev環境向けアプリをビルドします。'
  lane :build_dev do
    flavor = 'dev'
    export_options_plist_path = './ios/ExportOptions_dev.plist'

    build(
      flavor: flavor,
      export_options_plist_path: export_options_plist_path
    )
  end

  desc 'Prod環境向けアプリをビルドします。'
  lane :build_prod do
    flavor = 'prod'
    export_options_plist_path = './ios/ExportOptions_prod.plist'

    build(
      flavor: flavor,
      export_options_plist_path: export_options_plist_path
    )
  end

  desc 'Dev環境向けアプリを電子署名なしにビルドします。'
  lane :build_dev_with_no_code_sign do
    flavor = 'dev'

    Dir.chdir('../../') do
      sh(
        'flutter build ipa '\
        "--flavor #{flavor} "\
        '--no-codesign'
      )
    end
  end

  desc 'Dev環境向けアプリをApp Storeにデプロイします。'
  lane :deploy_dev do
    Dotenv.load '.env'

    apple_api_issuer_id = ENV['APPLE_API_ISSUER_ID'].to_s
    apple_api_key_id = ENV['APPLE_API_KEY_ID'].to_s
    external_tester_groups_string = ENV['EXTERNAL_TESTER_GROUPS'].to_s
    external_tester_groups = external_tester_groups_string.split(',')

    # action で利用するパスなので、fastlane コマンドを実行するディレクトリからの相対パスで指定
    app_store_connect_api_key_path = 'fastlane/app-store-connect-api-key.p8'

    release_notes = generate_release_notes

    build_dev

    api_key = app_store_connect_api_key(
      key_id: apple_api_key_id,
      issuer_id: apple_api_issuer_id,
      key_filepath: app_store_connect_api_key_path
    )

    upload_to_testflight(
      api_key:,
      changelog: release_notes,
      distribute_external: true,
      groups: external_tester_groups
    )
  end

  desc 'Prod環境向けアプリをApp Storeにデプロイします。'
  lane :deploy_prod do
    Dotenv.load '.env'

    apple_api_issuer_id = ENV['APPLE_API_ISSUER_ID'].to_s
    apple_api_key_id = ENV['APPLE_API_KEY_ID'].to_s
    external_tester_groups_string = ENV['EXTERNAL_TESTER_GROUPS'].to_s
    external_tester_groups = external_tester_groups_string.split(',')

    # action で利用するパスなので、fastlane コマンドを実行するディレクトリからの相対パスで指定
    app_store_connect_api_key_path = 'fastlane/app-store-connect-api-key.p8'

    release_notes = generate_release_notes

    build_prod

    api_key = app_store_connect_api_key(
      key_id: apple_api_key_id,
      issuer_id: apple_api_issuer_id,
      key_filepath: app_store_connect_api_key_path
    )

    upload_to_testflight(
      api_key:,
      changelog: release_notes,
      distribute_external: true,
      groups: external_tester_groups
    )
  end

  private_lane :build do |options|
    flavor = options[:flavor]
    dart_defines_path = options[:dart_defines_path]
    export_options_plist_path = options[:export_options_plist_path]

    dart_defines_command_part = if dart_defines_path.nil?
                                  ''
                                else
                                  "--dart-define-from-file '#{dart_defines_path}'"
                                end
    archive_path = './build/ios/Runner.xcarchive'

    Dir.chdir('../../') do
      sh(
        'flutter build ios '\
        "--flavor #{flavor} "\
        "#{dart_defines_command_part} "\
        '--no-codesign'
      )

      # workspace の以下設定を無視してビルドするために flutter コマンドではなく xcode コマンドを利用
      # - Code Signing Style = Automatic
      # - Code Signing Identity = iPhone Developer
      # これらの設定は、開発マシンでビルドする際に効率的な設定であるため、残しておきたい
      sh(
        'set -o pipefail && '\
        'xcodebuild archive CODE_SIGNING_ALLOWED=NO '\
        '-workspace ./ios/Runner.xcworkspace '\
        "-scheme '#{flavor}' "\
        "-configuration 'Release-#{flavor}' "\
        "-archivePath #{archive_path}"
      )

      sh(
        'set -o pipefail && '\
        'xcodebuild -exportArchive '\
        "-archivePath #{archive_path} "\
        '-exportPath ./build/ios/ipa '\
        "-exportOptionsPlist #{export_options_plist_path} "\
        '-allowProvisioningUpdates'
      )
    end

    lane_context[SharedValues::IPA_OUTPUT_PATH] =\
      '../build/ios/ipa/pochi_trim.ipa'
  end
end
