# frozen_string_literal: true

# このファイルは、ios/fastlane/Fastfile と android/fastlane/Fastfile からインポートされ、呼び出される想定です。
# そのため、カレントディレクトリが ios/fastlane または android/fastlane となっている前提で処理しています。

desc 'Flutterの依存関係をインストールします。'
lane :install_flutter_dependencies do
  Dir.chdir('../../') do
    sh('flutter pub get --no-example')
  end
end

desc '自動コードを生成します。'
lane :generate do
  install_flutter_dependencies

  Dir.chdir('../../') do
    sh('dart run build_runner build')
  end
end
